#!/usr/bin/env  python
#-*- coding: utf-8 -*-
res_pre='1718'
res_url='http://acm.sdibt.edu.cn/JudgeOnline/contestrank.php?cid='
from bs4 import BeautifulSoup
import urllib.request
if __name__== '__main__':
    res_url += res_pre
    response = urllib.request.urlopen(res_url)
    soup = BeautifulSoup(response,"lxml",from_encoding="utf-8")
    print("网页标题:"+soup.title.string)#获取标题
    '''
    获取题目数量
    '''
    sum = 0
    for s in soup.findAll('a'):
       if s.string is not None:
            if len(s.string)==1 and "A" <= s.string[0] <= "Z":
                #print("--"+s.string+"--")
                sum+=1
    print("题目数:", end="")
    print(sum)
    '''获取各种量'''
    num=1
    for res_tem in soup.findAll(align='center'):
        if 'evenrow' in str(res_tem) or 'oddrow' in str(res_tem):
            print(num)#序号
            num+=1
            print(res_tem.a.string)#学号
            res_tem1=res_tem.td
            res_tem1 = res_tem1.find_next('a')
            res_tem1 = res_tem1.find_next('a')
            print(res_tem1.string)#姓名
            res_tem1 = res_tem1.find_next('td')
            print(res_tem1.string)#做出题目数Solved
            res_tem1 = res_tem1.find_next('td')
            print(res_tem1.string)#做题总时长Penalty
            for i in range(sum):
                res_tem1 = res_tem1.find_next('td')
                res_tem2 = res_tem1.getText('*').split("*")
                if res_tem2[0] != '':
                    print(res_tem2[0])
                else:
                    print('NULL')